### ISSUE TITLE
server.js 4.6 latest version crashes when opening Stremio

### ISSUE THREAD

**Issue by alexandru-balan** [Stremio/stremio-shell#93]
Hi I have recently rebuilt Stremio from master branch and everything went fine. It built, it installed correctly but the server.js component is broken. 
The following message is shown upon opening the app : 
```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

fs.js:128
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:128:9)
    at Object.writeFile (fs.js:1163:14)
    at Object.Settings.self.save (/opt/stremio/server.js:134185:6)
    at Object.Settings.self.load (/opt/stremio/server.js:134191:9)
    at Settings (/opt/stremio/server.js:134208:7)
    at Object.require.718../cache (/opt/stremio/server.js:132868:37)
    at s (/opt/stremio/server.js:1:338)
    at e (/opt/stremio/server.js:1:509)
    at Object.<anonymous> (/opt/stremio/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by Ivshti** [comment]
It seems we've missed a callback. This works in older versions of NodeJS but doesn't work in newer ones. We'll fix ASAP

**Comment by alexandru-balan** [comment]
Hi sorry it took so long to verify this, everything is fixed now, thanks a lot. I will close the issue as it is no longer relevant.

**Comment by jaruba** [comment]
ma bucur, cu placere ;)
